# Generated by Django 2.2 on 2021-08-02 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210802_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='post',
            name='start_time',
        ),
    ]
